# Generated by Django 6.0.6 on 2026-07-15 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=50, unique=True)),
                ('type_operation', models.CharField(choices=[('IMPORT', 'Importation'), ('EXPORT', 'Exportation')], max_length=10)),
                ('produit', models.CharField(max_length=150)),
                ('quantite', models.PositiveIntegerField()),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=12)),
                ('devise', models.CharField(default='MAD', max_length=3)),
                ('pays_origine', models.CharField(max_length=100)),
                ('pays_destination', models.CharField(max_length=100)),
                ('date_operation', models.DateField()),
                ('date_livraison', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PLANIEFIEE', 'Planifiée'), ('EN_TRANSIT', 'En transit'), ('LIVREE', 'Livrée'), ('ANNULEE', 'Annulée')], default='PLANIEFIEE', max_length=20)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
