# Generated by Django 6.0.6 on 2026-07-20 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='status',
            field=models.CharField(choices=[('PLANIFIEE', 'Planifiée'), ('EN_TRANSIT', 'En transit'), ('LIVREE', 'Livrée'), ('ANNULEE', 'Annulée')], default='PLANIFIEE', max_length=20),
        ),
    ]
